imports:
        - { resource: consumers.yml }
        - { resource: publishers.yml }
        - { resource: comparators.yml}

services:
    sorting:
        class: AppBundle\Service\SortService
        calls:
            - [addComparator, ['@comparator.greater_than']]
            - [addComparator, ['@comparator.lesser_than']]