imports:
        - { resource: consumers.yml }
        - { resource: publishers.yml }
        - { resource: comparators.yml }

services:
    sorting:
        class: AppBundle\Service\SortService
        calls:
            - [addComparator, ['@comparator.greater_than']]
            - [addComparator, ['@comparator.lesser_than']]
    rabbimq_provider:
        class: AppBundle\Service\Provider\RabbitProvider
        calls:
            - [setConnection, ['%amqp_default_host%', '%amqp_default_port%', '%amqp_default_user%', '%amqp_default_password%', '%amqp_default_vhost%']]
            - [setQueueName, ['%amqp_default_queue%']]
    message_providers:
        class: AppBundle\Service\Provider\MessageProvider
        calls:
            - [addProvider, ['@rabbimq_provider']]
    rabbimq_provider.decorator:
        class: AppBundle\Service\Provider\DecoratorRabbitProvider
        public: false
        decorates: rabbimq_provider
        arguments: ['@rabbimq_provider.decorator.inner']
        calls:
            - [setCacheProvider, ['@memcached']]

    comparator_service:
        class: AppBundle\Service\ComparatorService
        calls:
            - [setCacheProvider, ['@memcached']]
            - [setComparatorRepository, ['@doctrine']]
