<?php

namespace AppBundle\Repository;

/**
 * ComparatorFunctionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComparatorFunctionRepository extends \Doctrine\ORM\EntityRepository
{
}
